### ISSUE TITLE
Add Julia implementation

### ISSUE THREAD

**Issue by dfm** [dfm/GenRP#1]
cc @ericagol

**Comment by ericagol** [comment]
There is already a Gaussian Processes package written in Julia:

https://github.com/STOR-i/GaussianProcesses.jl

Might be nice to use similar syntax for ease of interfacing.

Also, we should try our codes out on the CO2 dataset!

**Comment by dfm** [comment]
I don't agree that that's a good interface. For example, it's useful to be able to reuse the factorized matrix on multiple different y values.

[I did try out the CO2 example](https://github.com/dfm/GenRP/blob/master/python/examples/co2.ipynb). This kernel can't really seem to capture the long-term trends so I had to include a polynomial mean.
