### ISSUE TITLE
Choose parameterization

### ISSUE THREAD

**Issue by dfm** [dfm/GenRP#2]
I think that for my purposes, the best parameterization would be: `log_amplitude`, `log_qfactor`, and `log_frequency`. In this parameterization, `alpha = exp(log_amplitude)`, `beta.real = exp(-log_qfactor)`, and `beta.imag = 2*pi*exp(log_frequency)`.

What would complex amplitudes be used for?

**Comment by ericagol** [comment]
A potential problem with this parameterization is that if a frequency of zero is used (for a non-oscillating, exponentially-decaying exponential), then log_frequency = -Inf.  This *may* cause problems with, say, computing derivatives with respect to model parameters.

One possible solution might be to define two kernel types:  1). an exponential kernel (with frequency = 0, so beta is real); 2). a kernel with complex beta.

Another choice to make is whether the user specifies the complex conjugate Lorentzian, or if the code adds this if it sees if there is a beta with a non-zero imaginary component.

**Comment by dfm** [comment]
I think we definitely want two kernels because it is nice to be able to fix the frequency to zero and you won't want to _fit_ for the frequency in that case. In the end, I went with this interface:

```
kernel = Kernel();
kernel.add_term(0.1, 0.2);
kernel.add_term(0.3, 0.4, 0.5);
```

which would give a kernel with the PSD:

```
P(f) = 2 e^{0.1} / (1 + (f/e^{0.2})^2) + e^{0.3} / (1 + ((f - e^{0.5})/e^{0.4})^2) + e^{0.3} / (1 + ((f + e^{0.5})/e^{0.4})^2)
```

**Comment by ericagol** [comment]
Also, we should allow the amplitude to be negative since, for example, a Matern kernel can be approximated by summing a positive & negative Lorentzian.

**Comment by dfm** [comment]
OK. The only issue with that is that terms with negative amplitudes are not valid on their own because k(0.0) >= 0.0 must be satisfied.

**Comment by ericagol** [comment]
Perhaps the total amplitude could be drawn from a logarithm, and the sums of the others would be constrained to add up to that value.

Eric Agol
Astronomy Professor
University of Washington
