### ISSUE TITLE
Typo in equation 3 of appendix?

### ISSUE THREAD

**Issue by dfm** [dfm/GenRP#24]
I get:

```
\sum_{j=1}^p \alpha_i l_{k,j}^R + d \, x_k + \sum_{j=1}^p \left[
\gamma_{k,j}^R r_{k+1,j}^R + \gamma_{k,j}^I r_{k+1,j}^I\right] = b_k,
```

– I don't agree with your factors of 2 but maybe I'm missing something!

**Comment by ericagol** [comment]
We differ by a factor of 4 for the \gamma coefficients.  The factor of 2 multiplying my \gamma coefficients came from the real part of the sum of \gamma r_{k+1} and \gamma^* r_{k+1}* which gives 2(\gamma_R r_{k+1,R} + \gamma_I r_{k+1,I}).  I then divided through the entire equation by 2 which gives factors of 1/2 multiplying \alpha, d & b.

**Comment by dfm** [comment]
We differ by a factor of 2. I had a typo when I first submitted this.

I still don't agree. If you just start with Eq 61:

```
a^T * l + d * x + (g_r - i*g_i)^T * (r_r - i*r_i) = b
```

this gives

```
a^T * l + d * x + g_r^T * r_r + g_i^T * r_i = b   and
g_i^T * r_r + g_r^T * r_i = 0
```

since `a`, `d`, `x`, and `b` are real.

**Comment by dfm** [comment]
oops. that last equation should have a `l_i` in it too but that doesn't change what I was saying!

**Comment by dfm** [comment]
Oh duh. I suck. I get what you're saying.

**Comment by ericagol** [comment]
No, you definitely don't suck.  I took me a few tries to get this right!

Eric Agol
Astronomy Professor
University of Washington
