### ISSUE TITLE
Quality factor

### ISSUE THREAD

**Issue by dfm** [dfm/GenRP#36]
@ericagol: you mentioned that the Q-factor should be dimensionless. I think I should actually be d/c or d/2c. This will have the right units and it is (omega_0) / (delta omega) as it should be!

**Comment by ericagol** [comment]
@dfm I think it can be gotten from equations (24)-(25), but perhaps it simplifies to one of those limits in this case?

Eric Agol
Astronomy Professor
University of Washington

**Comment by ericagol** [comment]
Comparing equations (10) & (34), d_j = \omega_0 (which is the limit for Q >> 1), and c_j = \omega_0/(2Q), so Q = d_j/(2c_j).

**Comment by dfm** [comment]
The quality factor of a resonance is just the resonant frequency over the width of the resonance so it had better have that form! The question was just whether c was the "half-width" or the "width". It really is a question of definitions here. I'm happy to use the definition implied by the SHO model.
